/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Modelo.Cuenta;
import Modelo.GestorCuentasMem;
import Modelo.ServicioCuentas;

/**
 *
 * @author Luisf
 */
public class IFrmMovimientos extends javax.swing.JInternalFrame {
    
    private ServicioCuentas servicioCuentas;

    /**
     * Creates new form IFrmMovimientos
     */
    public IFrmMovimientos() {
        initComponents();
        servicioCuentas = new ServicioCuentas(new GestorCuentasMem());
        txtMovi.addItem("Depositar");
        txtMovi.addItem("Retirar");
        txtMovi.addItem("Transferir");
    }
    
    private void realizarMovimiento() {
    try {
        String cuentaOrigen = txtCuenOri.getText().trim();
        String cuentaDestino = txtCueDes.getText().trim();
        String tipoMovimiento = (String) txtMovi.getSelectedItem();
        String saldoStr = txtSaldo.getText().trim();

        if (saldoStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe ingresar un saldo válido.");
            return;
        }

        double monto = Double.parseDouble(saldoStr);

        switch (tipoMovimiento) {
            case "Depositar":
                servicioCuentas.depositar(cuentaOrigen, monto);
                javax.swing.JOptionPane.showMessageDialog(this, "Depósito realizado con éxito.");
                break;

            case "Retirar":
                servicioCuentas.retirar(cuentaOrigen, monto);
                javax.swing.JOptionPane.showMessageDialog(this, "Retiro realizado con éxito.");
                break;

            case "Transferir":
                servicioCuentas.tranferir(cuentaOrigen, cuentaDestino, monto);
                javax.swing.JOptionPane.showMessageDialog(this, "Transferencia realizada con éxito.");
                break;

            default:
                javax.swing.JOptionPane.showMessageDialog(this, "Movimiento no reconocido.");
                break;
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El monto debe ser un número válido.");
    } catch (IllegalArgumentException | IllegalStateException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage());
    }
    }
    
    private void buscarCuentaYMostrarSaldo() {
    try {
        String numeroCuenta = txtCuenOri.getText().trim();

        if (numeroCuenta.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ingrese un número de cuenta.");
            return;
        }

        Cuenta cuenta = servicioCuentas.buscar(numeroCuenta);
        if (cuenta == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Cuenta no encontrada.");
            txtSaldo.setValue(null);
        } else {
            txtSaldo.setValue(cuenta.getSaldo());
            javax.swing.JOptionPane.showMessageDialog(this, "Cuenta encontrada. Saldo actual: " + cuenta.getSaldo());
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar la cuenta: " + e.getMessage());
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMovi = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCueOri = new javax.swing.JLabel();
        txtCuenOri = new javax.swing.JFormattedTextField();
        lblCueDes = new javax.swing.JLabel();
        txtCueDes = new javax.swing.JFormattedTextField();
        txtMovi = new javax.swing.JComboBox<>();
        lblMovim = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        lblMovi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblMovi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovi.setText("Movimientos");

        lblCueOri.setText("Cuenta Origen");
        lblCueOri.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                lblCueOriAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        try {
            txtCuenOri.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCuenOri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuenOriActionPerformed(evt);
            }
        });

        lblCueDes.setText("Cuenta Destino");

        try {
            txtCueDes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#################")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblMovim.setText("Movimiento");

        lblSaldo.setText("Saldo");

        txtSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/buscar.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Iconos/aceptar.png"))); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCueOri, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuenOri, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnBuscar)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMovim)
                            .addComponent(txtMovi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCueDes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCueDes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar)
                        .addGap(60, 60, 60))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCueOri, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCueDes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCuenOri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCueDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovim)
                    .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMovi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMovi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCueOriAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_lblCueOriAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCueOriAncestorMoved

    private void txtCuenOriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuenOriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuenOriActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarCuentaYMostrarSaldo();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        realizarMovimiento();
    }//GEN-LAST:event_btnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCueDes;
    private javax.swing.JLabel lblCueOri;
    private javax.swing.JLabel lblMovi;
    private javax.swing.JLabel lblMovim;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JFormattedTextField txtCueDes;
    private javax.swing.JFormattedTextField txtCuenOri;
    private javax.swing.JComboBox<String> txtMovi;
    private javax.swing.JFormattedTextField txtSaldo;
    // End of variables declaration//GEN-END:variables
}
